application:
  Port: ":8090"
  ReadTimeout: 20
  WriteTimeout: 20
  ExpireTime: 10
  DocProcPoolSize: 20
  MaxCurrThread: 3
  UserService: false
  ReportError: false
  DataSource:
    dsn: root:enf@123@tcp(event_db:3306)/eventdb?charset=utf8mb4&parseTime=True&loc=Local
    maxidleconnections: 10
    maxopenconnections: 5
    name: docDatabase
    type: mysql
  Security:
    Registration: true
    MaxTryTimes: 10
    ForbidAccessTime: 5.0
    DefaultAdminPWD: "admin@123"
  AppSecret:
    AccessKey: 1233333333
    SecretKey: hsdf11212
  AccessControlAllowOrigin: false
  AccessControlAllowHost: "*"
  AccessControlAllowMethods: "POST, GET, OPTIONS"
  AccessControlAllowHeaders: "Content-Type"
  Web:
    vip: "/out/vip"
    pri: "/out/pri"
  StaticDir:
    RelativePath: "/s"
    AbsoluteFileDir: "/usr/www"
